### ISSUE TITLE
Implement Payment/Donation with Stripe

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/Future-Fresh#7]
# Motivation
We want the user to be able to make one-time or recurring payments/donations. 

# Implementation Details
We will use Stripe to handle the transactions. 

# Feature Details
Users should be able to select from **3 payment options**. 

1. Basic: $12.50
2. Premium: $17.50
3. Donation (dropdown)
    - Founding Donor: $20
    - Any

# Tasks

- [x] Implement Stripe front-end element
- [x] Customize payment form
- [x] Set up SSL
- [x] Handle Stripe charge (back-end) (need to get the payment type (premium/basic, and send that to backend and create charge amount based on that selection.))
- [x] Verify / Activate Stripe Account.
- [x] Test a live transaction and reset to live amount. 
- [ ] Clear customer information once payment form is submitted.
- [ ] Add Stripe badge to payment form.
